[project]
name = "data-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "David Molizane", email = "david.molizane@icloud.com" }
]
requires-python = ">=3.13"
dependencies = [
    "playwright>=1.62.0",
]

[project.scripts]
pdf-convert = "data_planner.pdf:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
